version: "3"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8100:80
    environment:
      - PMA_ARBITRARY=1
      #- PMA_HOST=mysql-5.7
    networks:
      - web

networks:
  web:
    external: true
    
    
    
    
    
