version: "3"
services:
  db:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always
    volumes:
      - ~/dockerQA/db/mysql-5.7/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYQSL_PASSWORD: root
    networks:
      - web

networks:
  web:
    external: true
    
    
    
    
    
