version: "3"
services:
  php71:
    build:
      dockerfile: php-7.1.Dockerfile
      context: .
    container_name: php-7.1
    restart: always
    volumes:
      - ~/dockerQA/html/:/var/www/html
      - ~/dockerQA/php/config/php71/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 8071:80
    networks:
      - web

  php72:
    build:
      dockerfile: php-7.2.Dockerfile
      context: .
    container_name: php-7.2
    restart: always
    volumes:
      - ~/dockerQA/html/:/var/www/html
      - ~/dockerQA/php/config/php72/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 8072:80
    networks:
      - web

  php73:
    build:
      dockerfile: php-7.3.Dockerfile
      context: .
    container_name: php-7.3
    restart: always
    volumes:
      - ~/dockerQA/html/:/var/www/html
      - ~/dockerQA/php/config/php73/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 8073:80
    networks:
      - web

  php74:
    build:
      dockerfile: php-7.4.Dockerfile
      context: .
    container_name: php-7.4
    restart: always
    volumes:
      - ~/dockerQA/html/:/var/www/html
      - ~/dockerQA/php/config/php74/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 8074:80
    networks:
      - web

networks:
  web:
    external: true
    
    
    
    
    
